### ISSUE TITLE
Markdown filetype support

### ISSUE THREAD

**Issue by Taknamay** [gottcode/focuswriter#159] opened 2015-04-07 22:17 UTC
Hi,

I saw there were two issues already about Markdown support, but they were about syntax support. I just want support for the Markdown filetype for reading and writing.

Just as an explanation for my preference, I looked at how .rtf files are internally, and they include a lot of information that I feel is unnecessary. I like Markdown because 99% of the file content is the actual text, and not meta data. It's just some small extensions to .txt that let you have italics, bold, and headers. Every once in a while, I want to get down and dirty with the plaintext of the file, and .rtf is harder to do that with.

I am not sure how hard it would be to implement, but it would be great (for me). Until then I will stick to .rtf for basic formatting.

Thanks for making the software. I am enjoying it so far except for this one feature! :)

**Comment by gottcode** [comment] 2015-04-11 12:55
The .rtf files from FocusWriter don't include anything extraneous, so I'm not entirely sure what you would gain from using Markdown instead. Also, there is a fair amount of formatting that is in Markdown that is not supported by FocusWriter, and some formatting in FocusWriter that is not in Markdown. Still, I will think about it.

**Comment by ChuckDaniels87** [comment] 2015-04-20 12:44
+1 - It would be nice to have this feature implemented.

**Comment by Norlick** [comment] 2015-06-04 11:36
+1 - FocusWriter is great, but I'd actually use it if it exported to Markdown.

**Comment by kodermike** [comment] 2015-07-24 06:43
:+1: for md support (but native, not just exporting or importing). Which is a lot of work, so I'm not holding my breath, but you have my vote just in case :)

**Comment by gottcode** [comment] 2015-07-24 10:03
FocusWriter's development is not a democracy, and the next time I get a "+1" comment I will close this issue. Please stop. Give reasons. Why do you want this? What is it for?

Nobody has given me a persuasive reason to add Markdown support. In my view, it is a format that is only useful when you need a way to write HTML inside of HTML (such as blog posts); that has never been nor will ever be the purpose of FocusWriter.

As I stated before: Markdown supports many things that FocusWriter *never* will (tables, links, raw HTML, etc). FocusWriter supports some formatting that Markdown requires raw HTML for. This format is not a good fit for FocusWriter.

Why should I add support for it? What uses does it bring? I see none. Please enlighten me.

**Comment by ChuckDaniels87** [comment] 2015-07-24 10:10
It's a nice way to quick formatting a text, not only for _HTML_. If you want to share a document formatted the most reasonable way is to send a _PDF_ to someone without considering if they are using ODF compatible software. So, it would be a nice feature to directly export a Markdown document to PDF directly in _FocusWriter_.

Good job anyways with this piece of software. :wink:

**Comment by gottcode** [comment] 2015-07-24 10:40
Why not just print to PDF, if what you want is a PDF document? Every operating system I have tested FocusWriter on has that as option. Otherwise, you would still need a conversion from Markdown to PDF, and all of the tools I have seen that convert Markdown also support ODT and RTF.

**Comment by ChuckDaniels87** [comment] 2015-07-24 10:46
The point is that Markdown allows user to quick-formatting text. You can format your text in ODT and create a very nice document but that is not quick-formatting. It seems logical to me that a text editor whose objetive is focused writting implements some kind of quick-formatting language.

**Comment by gottcode** [comment] 2015-07-24 10:59
Oh, I'm never adding Markdown *editing* to FocusWriter. I'm completely opposed to that. The only thing I am considering adding (but not convinced about) is the ability to save and open Markdown files. From the perspective of actually using FocusWriter it would be the same as saving and opening ODT.

For quickly formatting your text, just use keyboard shortcuts. The basics like bold, italic, and underline have been the same between text editors *for decades* and are just as fast as adding random symbols to the text.

**Comment by ChuckDaniels87** [comment] 2015-07-24 11:10
I didn't mean editing Markdown because they are simple plain text files just with a bunch of file extensions (.md, .markdown,...). Markdown is gaining momentum because is easily editable anywhere (any text editor) and still readable without processing it. So it would be nice simply exporting this kind of files to PDF. 

Thanks for answering and keep developing this awesome editor! :+1:

**Comment by kodermike** [comment] 2015-07-24 15:21
@gottcode Didn't mean to upset you with my thumbs, simply intended to share in interest in the question. Thank you for taking the time to respond and provide an insight into your development roadmap for FocusWriter and your position on MD. 

To explain briefly my interest, MD is a poor man's latex. It allows one to edit plain text files with formatting that can then be exported to a number of formats directly. 

Thanks again for FocusWriter, it is an awesome editor.

**Comment by gottcode** [comment] 2015-07-24 19:32
@kodermike Thank you for explaining why you want this. Sorry to get cranky; it's a pet peeve of mine to see feature requests or bug reports get "+1" comments if they don't also add substance to the discussion.

I can understand the idea of a poor man's LaTeX. I'm not yet sold on that as a good enough justification, but I will consider it.

One of my hesitations about adding any new file formats is that they add constraints on what features I can add in the future. I don't want to have some file formats not be able to save everything. I also can't easily drop them in the future if I change my mind. And then I have to write support for reading and writing any new formatting feature for every single file format, potentially introducing new bugs along the way.

Plain text, thankfully, is not expected to support anything at all. RTF, on the other hand, has made me not consider a few features because it can't (or badly) supports things that ODT and OOXML can. Markdown is a somewhat simplistic format that doesn't completely cover the same features FocusWriter already supports.

Would flat ODT be able to serve as a poor man's LaTeX? After all, it is a plain text file that contains all of the markup--just a little more baroque as it is the XML of a zipped ODT file merged into a single text file. It feels close to writing HTML, actually. And I have already added support for it in git, because it adds no more constraints than ODT has and can reuse the ODT parsing logic.

**Comment by beedaddy** [comment] 2015-12-15 15:02
@gottcode You said that MarkDown is (more or less) only useful for blog posts etc. Another use case is writing books. For example, with MarkDown and pandoc it is easy to create ebooks (epub). Support for MarkDown would fit perfectly to the workflow of a fiction writer. Writing distraction-free with FocusWriter. Convert the MarkDown-text to various formats with pandoc. In case of epub: Polish with calibre, sigil or whatever and publish book. Sounds good to me. :)

**Comment by gottcode** [comment] 2015-12-15 16:02
@beedaddy Except that is also true of other file formats like ODT. After all, pandoc also supports using ODT as an input format. You can convert the ODT file to EPUB, and then improve it in Sigil. No need for Markdown. :)

**Comment by kodermike** [comment] 2015-12-15 17:16
If I could add - the thing I know I failed to take into account is that FocusWriter already supports (multi)markdown, in so much as (m)md is supposed to be a text format that can be edited by any text editor, regardless of format support. I've been writing markdown happily in FocusWriter since my original comment - just remember to save as plain text, and you're fine. Sure, it would be nice if *.md,*.mmd was part of the list of text formats for automatic selection when opening a new document, but  selecting All Files (*) in FocusWriter works just as well.

**Comment by beedaddy** [comment] 2015-12-16 07:11
@gottcode Yes, but then it should be possible to create chapters in ODT (perhaps I missed that? I'm new to FocusWriter). With markdown you can do that even without any shortcuts or menu items. Which is even more distraction-free. Syntax highlighting would be nice, of course. :) Just my 2 cents.

**Comment by Taknamay** [comment] 2015-12-16 13:41
The idea of flat ODT appeals to me, but I would still like markdown support. I don't think you need to worry about it restricting features; can't you just throw away information for markdown? Personally, I have about the same expectations that markdown would save the same information as plaintext.

**Comment by gottcode** [comment] 2015-12-19 12:47
@kodermike True, the simplest "support" would be to just add ```.md``` and ```.mmd``` to the plain text format selection. Unfortunately, then some people would start requesting synatx highlighting for Markdown, which I absolutely will not add.

@beedaddy The git version of FocusWriter has headings support, but no released version does. FocusWriter will support six levels of headings, so you could just use "Heading 1" for your chapters. That is as much support for "chapters" that Markdown has, after all. A quick check shows that pandoc treats each "Heading 1" in an ODT file as a chapter during conversion to epub.

Even if I add opening and saving Markdown to FocusWriter, you would still be using keyboard shortcuts or menu items to change formatting. The markup will be invisible, just like when saving to ODT, OOXML, or RTF. You wouldn't by typing Markdown into FocusWriter.

@Taknamay I do not like the idea of not saving everything that the user did with their file. Especially as FocusWriter doesn't have that much formatting; it just feels wrong to tell a user that they are going to lose some of that basic formatting when they go to save.

**Comment by gottcode** [comment] 2015-12-26 12:14
After much consideration, I have decided not to add Markdown as a file format to FocusWriter. I am sorry to dissapoint people.

To help make my decision, I actually programmed up reading and writing support in a local branch. It was an even worse fit than I had expected (no blank paragraphs and no tabs at the start of paragraphs were both things I had not even realized until then). Markdown is just fine for what is was designed for--being a simpler way to write HTML--but I stand by the view that it is not a good fit for FocusWriter.

You can still write Markdown in plain text files, as FocusWriter will not stop you. I may even add it to the list of plain text formats along with ```txt``` and ```text```, but I will not be adding anything else.

**Closed by gottcode** 2015-12-26 12:14 UTC
